### ISSUE TITLE
Warning: mysqli: Connection refused

### ISSUE THREAD

**Issue by Tabaluga** [ACSPRI/quexf-docker#2]
Dear @adamzammit,

thanks for your Docker image.

Today I've been setting up a new system and tried to run the newest queXF version with `docker-compose`, but the validation won't recognize the marked answers during the validation and I want to ask for your help.

Checking the log in the background shows the following two warnings - perhaps these are the cause of the missing recognition:

```bash
quexf-app | Warning: mysqli::__construct(): (HY000/2002): Connection refused in Standard input code on line 15
quexf-app | MySQL Connection Error: (2002) Connection refused
```

Thanks for your support and your help.
best regards

**Comment by adamzammit** [comment]
Hi @Tabaluga ,

That error message is normal while the app is starting up as it waits for the mysql container to be ready.

Not recognising marked answers is probably more due to the "filled" settings in queXF. Please see the queXF config.default.php for details. These can be adjusted in the container by using the following environment settings:

QUEXF_SINGLE_CHOICE_MIN_FILLED
QUEXF_SINGLE_CHOICE_MAX_FILLED
QUEXF_MULTIPLE_CHOICE_MIN_FILLED
QUEXF_MULTIPLE_CHOICE_MAX_FILLED

Adam

**Comment by adamzammit** [comment]
Also please use this repository: https://github.com/adamzammit/quexf-docker

for the latest code.
